[[headers]]
for = "/.well-known/assetlinks.json"
[headers.values]
Content-Type = "application/json"
Access-Control-Allow-Origin = "*"
[[headers]]
for = "/*.js"
[headers.values]
Content-Type = "text/javascript"