// Language translations
const translations = {
    en: {
        title: "Calendar",
		todayText: "Today",
		notePlaceholder: "Add your note here...",
		save: "Save",
		close: "Close",
		existingNotes: "Existing Notes",
		validationError: "Please select a color, type and enter note text",
		delete: "Delete",
		confirmDelete: "Are you sure you want to delete this note?",
		storageWarning: "Your storage is almost full. Some features may not work properly.",
		clearStorage: "Clear old data",
		updateAvailable: "New version available!",
		reload: "Reload",
		storageCleared: "Old data cleared successfully",
		storageError: "Error clearing old data",
		Install: "Install App",
        months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        icons: {
            plate: "Plate",
            health: "Health",
            mechanics: "Mechanics"
		},
		calendarSystems: {
			gregorian: "Gregorian",
			hijri: "Islamic Hijri"
		},
		monthsHijri: [
			"Muharram",
			"Safar",
			"Rabi' al-Awwal",
			"Rabi' al-Thani",
			"Jumada al-Awwal",
			"Jumada al-Thani",
			"Rajab",
			"Sha'ban",
			"Ramadan",
			"Shawwal",
			"Dhu al-Qidah",
			"Dhul-Hijjah"
		],
		back: "Back",
		delai: "Frequency",
		offlineSave: "Note saved offline. Will sync when online",
		backgroundSync: "Background sync active",
		periodicUpdate: "Daily updates enabled",
		notesReminder: "You have {count} notes for today",
		dailyTip: "Daily Tip",
		noTipToday: "No tip for today",
		noNotesToday: "No notes for today",
		sanitizeWarning: "Note : Special caracters will be cleaned automatically",
		validationErrorText: "Enter the note's text",
		edit: "Edit",
		noteSettings: "Note Settings",
		noteLabel: "Note Content",
		modalClose: "Close modal",
		onlineStatus: "Online",
		offlineStatus: "Offline",
		storageUsage: "Using {percentage}% of available storage",
		databaseError: "Database error. Some features may not work properly.",
		fileTooLarge: "File is too large to save offline",
		fileReadError: "Failed to read file",
		cleanupError: "Error during cleanup",
		loading: "Loading...",
		noEventsToday: "No events today",
		addAttachment: "Add attachment",
		attachmentSaved: "Attachment saved",
		attachmentError: "Failed to save attachment",
		noteSaved: "Note saved",
		noteUpdated: "Note updated",
		syncProgress: "Sync in progress...",
		syncCompleted: "Sync completed",
		syncFailed: "Sync failed",
		offlineMessage: "Offline - data unavailable",
		offlineBadge: "Offline",
		themeToggle: "Toggle Dark Mode",
		searchPlaceholder: "Search notes...",
		exportButton: "Export PDF",
		navigation: {
			scrollUp: "Scroll up",
			scrollDown: "Scroll down",
			tipCount: "Tip {current} of {total}"
		},
		descriptionLabel: "Description", // For the "📝" label
		frequencyLabel: "Frequency",     // For the "⏰" label
		time: "Time",
		memory: "Memory",
		memoryMonitor: "Memory Monitor",
		clearPartial: "Clear Partial Data",
		clearAll: "Clear All Data",
		clearOptions: "Clear Options",
		notesByMonth: "Notes by Month",
		clear: "Clear",
		clearAllWarning: "WARNING: Data Deletion",
		clearAllNotes: "All notes",
		clearAllAttachments: "All attachments",
		clearAllSync: "Sync queue",
		clearAllLocalStorage: "LocalStorage data",
		clearAllWarningText: "This action cannot be undone. Make sure to export important data first.",
		cancel: "Cancel",
		clearConfirm: "Clear Selected Data",
		autoCleanup: "Automatic Cleanup",
		autoCleanupTooltip: "Automatically cleans old data every 15 days",
		monthCleared: "Month data cleared",
		confirmDeleteSingleNote: "Delete this specific note?",
		noteDeleted: "Note deleted",
		attachmentDeleted: "Attachment deleted",
		deleteError: "Error deleting",
		seeMore: "See More",
		localStorageWarning: "Clearing localStorage will reset all preferences and cached data",
		periodicActivities: "Periodic Activities",
		emergencyCleanup: "Auto-clean when storage full",
		emergencyCleanupTooltip: "Automatically cleans old data when storage reaches 90% capacity",
		storageWarning90: "Your storage is 90% full. Clean old data?",
		storageClearing: "Cleaning old data to free space...",
		syncOptions: {
			storage: "Sync Storage (LocalStorage ↔ DB)",
			storageTooltip: "Keep LocalStorage and IndexedDB in sync automatically",
			version: "Auto-update App",
			versionTooltip: "Automatically install new versions when available",
			calendar: "Sync Calendar Systems",
			calendarTooltip: "Keep Gregorian and Hijri dates synchronized",
			newVersion: "New version available!",
			updating: "Updating to new version..."
		},
		enableNotifications: "Would you like to enable notifications?",
		testNotification: "Test Notification",
		notificationsUnsupported: "Notifications not supported in this browser",
		notificationSettings: "Notification Settings",
		enableUpdateReminders: "Enable updates reminders",
		updateRemindersTooltip: "Get reminders when updates are available",
		enableDailyNotifications: "Enable daily notifications",
		dailyNotificationsTooltip: "Receive daily summary notifications",
		notificationSound: "Notification sound", 
		notificationTime: "Notification time",
		soundDefault: "Default",
		soundChime: "Chime", 
		soundBell: "Bell",
		soundNone: "None",
		memoryManagement: "Memory Management",
		synchronization: "Synchronization",
		storageUsed: "Storage Used",
		syncOptionsTitle: "Data Synchronization",
		updateOptionsTitle: "Update Settings",
		confirmCleanup: "Proceed with automatic cleanup?",
		generalResearch: "General Research",
		dateResearch: "Date Research",
		noteResearch: "Note Research",
		generalResearchDesc: "This will contain general search functionality across all data.",
		dateResearchDesc: "This will contain date-specific search functionality.",
		noteResearchDesc: "This will contain note content search functionality.",
		searchEverything: "Search everything...",
		search: "Search",
		findDates: "Find Dates",
		searchNotes: "Search Notes",
		searchAll: "Search All",
		searchTips: "Search Tips", 
		searchAttachments: "Search Attachments",
		noResultsFound: "No results found",
		searchDate: "Search by Date",
		searchTime: "Search by Time",
		searchType: "Search by Type",
		searchColor: "Search by Color",
		previewText: "Sample Text - 123 ABC abc",
        Notesspecials: {
			generalize: "Generalize Note",
			editSpecial: "Edit Special Note",
			deleteNotes: "Delete Notes",
			generalizeTooltip: "Create repeating notes based on patterns",
			editSpecialTooltip: "Edit existing special notes",
			deleteNotesTooltip: "Delete single or multiple notes",
			generalizeOptions: "Generalization Options",
			firstNoteDate: "First note date",
			repeatPattern: "Repeat pattern",
			includeWeekends: "Include weekends",
			durationLimit: "Duration limit",
			daily: "Daily",
			weekly: "Weekly",
			monthly: "Monthly",
			yearly: "Yearly",
			none: "None",
			saturday: "Saturday",
			sunday: "Sunday",
			both: "Both",
			year: "year",
			years: "years",
			custom: "Custom",
			confirm: "Confirm",
			editSpecialNotes: "Edit Special Notes",
			deleteNotesOptions: "Delete Notes Options",
			deleteSingle: "Delete single note",
			deleteAll: "Delete all notes",
			confirmDelete: "Confirm Delete",
			editSpecialNote: "Edit Special Note",
			selectNoteToDelete: "Select note to delete",
			confirmDeleteSingle: "Are you sure you want to delete this note?",
			confirmDeleteAll: "Are you sure you want to delete ALL special notes?",
            selectAll: "Select All",
            noNotesSelected: "Please select at least one note to delete",
            confirmDeleteSelected: "Are you sure you want to delete {0} selected notes?"
		},
        hijriConverter: {
            title: "Hijri Date Converter",
        hijriConverterTooltip: "Convert between Gregorian and Hijri dates",
        underDevelopment: "Under development",
            gregorianToHijri: "Gregorian to Hijri",
            hijriToGregorian: "Hijri to Gregorian",
            year: "Year",
            month: "Month",
            day: "Day",
            convert: "Convert",
            hijriDate: "Hijri Date",
            gregorianDate: "Gregorian Date",
            weekday: "Weekday",
            leapYear: "Leap Year",
            yes: "Yes",
            no: "No",
            hijriCalendar: "Hijri Calendar (Current Month)",
            gregorianCalendar: "Gregorian Calendar (Current Month)",
            invalidDate: "Invalid date",
            yearTooltip: "Enter the year in Gregorian calendar",
            monthTooltip: "Select the month",
            dayTooltip: "Enter the day of month",
            yearInputTooltip: "Enter year between 1 and 9999",
            convertTooltip: "Click to convert the date"
        },
	importExport: {
		exportData: "Export Data",
		importData: "Import Data",
		syncStatus: "Sync Status",
		exportDescription: "Export your calendar data to a file",
		importDescription: "Import calendar data from a file",
		exportAs: "Export as",
		exporting: "Exporting",
		importing: "Importing",
		exportCompleted: "Export completed successfully!",
		exportFailed: "Export failed",
		importComplete: "Import complete: {importedCount} notes imported, {skippedCount} skipped",
		importFailed: "Import failed",
		invalidFileFormat: "Invalid file format. Expected JSON data.",
		invalidDataFormat: "Invalid data format. Expected an object with date keys.",
		failedToImportNote: "Failed to import note:",
		calendarNotesExport: "Calendar Notes Export",
		generated: "Generated",
		totalDates: "Total Dates",
		totalNotes: "Total Notes",
		notesByDate: "Notes by Date",
		notesCount: "Notes Count",
		note: "Note",
		content: "Content",
		overwriteExisting: "Overwrite existing data",
		mergeExisting: "Merge with existing data",
		preparingExport: "Preparing export",
		// Tooltips
		exportJsonTooltip: "Export all notes in JSON format (recommended for backups)",
		exportCsvTooltip: "Export notes in CSV format (compatible with spreadsheets)",
		exportTxtTooltip: "Export notes in plain text format (human readable)",
		importTooltip: "Import notes from a previously exported file",
		overwriteTooltip: "Completely replace existing data with imported data",
		mergeTooltip: "Combine imported data with existing notes"
	}
	},
    ar: {
        title: "التقويم",
		todayText: "اليوم",
		notePlaceholder: "أضف ملاحظتك هنا...",
		save: "حفظ",
		close: "إغلاق",
		existingNotes: "الملاحظات الموجودة",
		validationError: "الرجاء اختيار لون ونوع وإدخال نص الملاحظة",
		delete: "مسح",
		confirmDelete: "هل أنت متأكد أنك تريد محو الملاحظة؟",
		storageWarning: "التخزين شبه ممتلئ. قد لا تعمل بعض الميزات بشكل صحيح.",
		clearStorage: "مسح البيانات القديمة",
		updateAvailable: "نسخة جديدة متوفرة!",
		reload: "إعادة التحميل",
		storageCleared: "تم مسح البيانات القديمة بنجاح",
		storageError: "خطأ أثناء مسح البيانات القديمة",
		Install: "تثبيت التطبيق",
        months: ["جانفي", "فيفري", "مارس", "أفريل", "ماي", "جوان", "جويلية", "أوت", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"],
        weekdays: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"],
        icons: {
            plate: "الطعام",
            health: "الصحة",
            mechanics: "الميكانيكا"
		},
		calendarSystems: {
			gregorian: "الميلادي",
			hijri: "الهجري"
		},
		monthsHijri: [
			"محرم",
			"صفر",
			"ربيع الأول",
			"ربيع الآخر",
			"جمادى الأولى",
			"جمادى الآخرة",
			"رجب",
			"شعبان",
			"رمضان",
			"شوال",
			"ذو القعدة",
			"ذو الحجة"
		],
		back: "رجوع",
		delai: "التكرار",
		offlineSave: "تم حفظ الملاحظة بدون اتصال. سيتم المزامنة عند الاتصال",
		backgroundSync: "مزامنة الخلفية نشطة",
		periodicUpdate: "تم تفعيل التحديثات اليومية",
		notesReminder: "لديك {count} ملاحظات لليوم",
		dailyTip: "نصيحة اليوم",
		noTipToday: "لا ملاحظات اليوم",
		noNotesToday: "لا ملاحظات اليوم",
		sanitizeWarning: "ملاحظة: تم تنظيف الأحرف الخاصة تلقائيًا",
		validationErrorText: "الرجاء إدخال نص الملاحظة",
		edit: "عدل",
		noteSettings: "إعدادات الملاحظة",
		noteLabel: "محتويات الملاحظة",
		modalClose: "إغلاق النافذة",
		onlineStatus: "متصل بالإنترنت",
		offlineStatus: "غير متصل",
		storageUsage: "يتم استخدام {percentage}٪ من مساحة التخزين المتاحة",
		databaseError: "خطأ في قاعدة البيانات. بعض الميزات قد لا تعمل بشكل صحيح.",
		fileTooLarge: "الملف كبير جدًا ولا يمكن حفظه دون اتصال",
		fileReadError: "فشل قراءة الملف",
		cleanupError: "خطأ أثناء التنظيف",
		loading: "جاري التحميل...",
		noEventsToday: "لا توجد أحداث اليوم",
		addAttachment: "إضافة مرفق",
		attachmentSaved: "تم حفظ المرفق",
		attachmentError: "فشل حفظ المرفق",
		noteSaved: "تم حفظ الملاحظة",
		noteUpdated: "تم تحديث الملاحظة",
		syncProgress: "جاري المزامنة...",
		syncCompleted: "تمت المزامنة",
		syncFailed: "فشلت المزامنة",
		offlineMessage: "غير متصل - البيانات غير متوفرة",
		offlineBadge: "غير متصل",
		themeToggle: "تبديل الوضع المظلم", 
		searchPlaceholder: "ابحث في الملاحظات...",
		exportButton: "تصدير PDF",
		navigation: {
			scrollUp: "التمرير لأعلى",
			scrollDown: "التمرير لأسفل",
			tipCount: "النصيحة {current} من {total}"
		},
		descriptionLabel: "الوصف",
		frequencyLabel: "التكرار",
		time: "وقت",
		memory: "الذاكرة",
		memoryMonitor: "مراقبة الذاكرة",
		clearPartial: "مسح جزئي للبيانات",
		clearAll: "مسح جميع البيانات",
		clearOptions: "خيارات المسح",
		notesByMonth: "الملاحظات حسب الشهر",
		clear: "مسح",
		clearAllWarning: "تحذير: حذف البيانات",
		clearAllNotes: "جميع الملاحظات",
		clearAllAttachments: "جميع المرفقات",
		clearAllSync: "طابور المزامنة",
		clearAllLocalStorage: "بيانات التخزين المحلي",
		clearAllWarningText: "لا يمكن التراجع عن هذا الإجراء. تأكد من تصدير البيانات المهمة أولاً.",
		cancel: "إلغاء",
		clearConfirm: "مسح البيانات المحددة",
		autoCleanup: "تنظيف تلقائي",
		autoCleanupTooltip: "تنظيف البيانات القديمة تلقائيًا كل 15 يومًا",
		monthCleared: "تم مسح بيانات الشهر",
		confirmDeleteSingleNote: "هل تريد حذف هذه الملاحظة المحددة؟",
		noteDeleted: "تم حذف الملاحظة",
		attachmentDeleted: "تم حذف المرفق",
		deleteError: "خطأ في الحذف",
		seeMore: "عرض المزيد",
		localStorageWarning: "مسح التخزين المحلي سيعيد تعيين جميع التفضيلات والبيانات المخزنة مؤقتًا",
		periodicActivities: "العمليات الدورية",
		emergencyCleanup: "تنظيف تلقائي عند امتلاء التخزين",
		emergencyCleanupTooltip: "يقوم بتنظيف البيانات القديمة تلقائيًا عندما يصل التخزين إلى 90% من السعة",
		storageWarning90: "التخزين ممتلئ بنسبة 90%. هل تريد تنظيف البيانات القديمة؟",
		storageClearing: "جاري تنظيف البيانات القديمة لتوفير مساحة...",
		syncOptions: {
			storage: "مزامنة التخزين (LocalStorage ↔ قاعدة البيانات)",
			storageTooltip: "الحفاظ على مزامنة LocalStorage و IndexedDB تلقائيًا",
			version: "تحديث التطبيق التلقائي",
			versionTooltip: "تثبيت الإصدارات الجديدة تلقائيًا عند توفرها",
			calendar: "مزامنة أنظمة التقويم",
			calendarTooltip: "الحفاظ على تواريخ التقويم الميلادي والهجري متزامنة",
			newVersion: "إصدار جديد متاح!",
			updating: "جارٍ التحديث إلى الإصدار الجديد..."
		},
		enableNotifications: "هل ترغب في تمكين الإشعارات؟",
		testNotification: "اختبار الإشعار",
		notificationsUnsupported: "الإشعارات غير مدعومة في هذا المتصفح",
		notificationSettings: "إعدادات الإشعارات",
		enableUpdateReminders: "تمكين تذكير التحديثات",
		updateRemindersTooltip: "الحصول على تذكير عند توفر التحديثات",
		enableDailyNotifications: "تمكين الإشعارات اليومية",
		dailyNotificationsTooltip: "تلقي إشعارات يومية ملخصة",
		notificationSound: "صوت الإشعار",
		notificationTime: "وقت الإشعار", 
		soundDefault: "افتراضي",
		soundChime: "جرس",
		soundBell: "جرس كبير",
		soundNone: "بلا",
		memoryManagement: "إدارة الذاكرة",
		synchronization: "المزامنة",
		storageUsed: "التخزين المستخدم",
		syncOptionsTitle: "مزامنة البيانات",
		updateOptionsTitle: "إعدادات التحديث",
		confirmCleanup: "المتابعة بالتنظيف التلقائي؟",
		storageError: "خطأ أثناء التنظيف",
		"generalResearch": "البحث العام",
		"dateResearch": "تاريخ البحث",
		"noteResearch": "ملاحظة البحث",
		"generalResearchDesc": "سيحتوي هذا على وظيفة البحث العامة عبر جميع البيانات.",
		"dateResearchDesc": "سيحتوي هذا على وظيفة البحث المتعلقة بالتاريخ.",
		"noteResearchDesc": "سيحتوي هذا على وظيفة البحث عن محتوى الملاحظات.",
		"searchEverything": "ابحث عن كل شيء...",
		"search": "بحث",
		"findDates": "ابحث عن التواريخ",
		"searchNotes": "ابحث عن الملاحظات",
		"searchAll": "البحث في الكل",
		"searchTips": "البحث في النصائح",
		"searchAttachments": "البحث في المرفقات", 
		"noResultsFound": "لا توجد نتائج",
		searchDate: "البحث حسب التاريخ",
		searchTime: "البحث حسب الوقت",
		searchType: "البحث حسب النوع",
		searchColor: "البحث حسب اللون",
		previewText: "عينة نصية 123 - أ ب ج",
        Notesspecials: {
			generalize: "تعميم الملاحظة",
			editSpecial: "تحرير ملاحظة خاصة",
			deleteNotes: "حذف الملاحظات",
			generalizeTooltip: "إنشاء ملاحظات متكررة بناءً على أنماط",
			editSpecialTooltip: "تعديل الملاحظات الخاصة الموجودة",
			deleteNotesTooltip: "حذف ملاحظة واحدة أو متعددة",
			generalizeOptions: "خيارات التعميم",
			firstNoteDate: "تاريخ الملاحظة الأولى",
			repeatPattern: "نمط التكرار",
			includeWeekends: "يشمل عطلة نهاية الأسبوع",
			durationLimit: "حد المدة",
			daily: "يومي",
			weekly: "أسبوعي",
			monthly: "شهري",
			yearly: "سنوي",
			none: "لا شيء",
			saturday: "السبت",
			sunday: "الأحد",
			both: "كلاهما",
			year: "سنة",
			years: "سنوات",
			custom: "مخصص",
			confirm: "تأكيد",
			editSpecialNotes: "تحرير الملاحظات الخاصة",
			deleteNotesOptions: "خيارات حذف الملاحظات",
			deleteSingle: "حذف ملاحظة واحدة",
			deleteAll: "حذف جميع الملاحظات",
			confirmDelete: "تأكيد الحذف",
			editSpecialNote: "تعديل ملاحظة خاصة",
			selectNoteToDelete: "حدد الملاحظة للحذف",
			confirmDeleteSingle: "هل أنت متأكد أنك تريد حذف هذه الملاحظة؟",
			confirmDeleteAll: "هل أنت متأكد أنك تريد حذف كل الملاحظات الخاصة؟",
            selectAll: "اختر الكل",
            noNotesSelected: "الرجاء اختيار ملاحظة واحدة على الأقل للحذف",
            confirmDeleteSelected: "هل أنت متأكد أنك تريد حذف {0} ملاحظة محددة؟"
		},
        hijriConverter: {
            title: "محول التاريخ الهجري",
        hijriConverterTooltip: "تحويل بين التواريخ الميلادية والهجرية",
        underDevelopment: "قيد التطوير",
            gregorianToHijri: "الميلادي إلى الهجري",
            hijriToGregorian: "الهجري إلى الميلادي",
            year: "السنة",
            month: "الشهر",
            day: "اليوم",
            convert: "تحويل",
            hijriDate: "التاريخ الهجري",
            gregorianDate: "التاريخ الميلادي",
            weekday: "اليوم",
            leapYear: "سنة كبيسة",
            yes: "نعم",
            no: "لا",
            hijriCalendar: "التقويم الهجري (الشهر الحالي)",
            gregorianCalendar: "التقويم الميلادي (الشهر الحالي)",
            invalidDate: "تاريخ غير صحيح",
            yearTooltip: "أدخل السنة في التقويم الميلادي",
            monthTooltip: "اختر الشهر",
            dayTooltip: "أدخل يوم الشهر",
            yearInputTooltip: "أدخل السنة بين 1 و 9999",
            convertTooltip: "انقر لتحويل التاريخ"
        },
    importExport: {
        exportData: "تصدير البيانات",
        importData: "استيراد البيانات",
        syncStatus: "حالة المزامنة",
        exportDescription: "قم بتصدير بيانات التقويم إلى ملف",
        importDescription: "استيراد بيانات التقويم من ملف",
        exportAs: "تصدير كـ",
        exporting: "جاري التصدير",
        importing: "جاري الاستيراد",
        exportCompleted: "تم التصدير بنجاح!",
        exportFailed: "فشل التصدير",
        importComplete: "اكتمل الاستيراد: تم استيراد {importedCount} ملاحظة، تخطي {skippedCount}",
        importFailed: "فشل الاستيراد",
        invalidFileFormat: "تنسيق ملف غير صالح. يتوقع بيانات JSON.",
        invalidDataFormat: "تنسيق بيانات غير صالح. يتوقع كائنًا بمفاتيح تاريخ.",
        failedToImportNote: "فشل استيراد الملاحظة:",
        calendarNotesExport: "تصدير ملاحظات التقويم",
        generated: "تم الإنشاء",
        totalDates: "إجمالي التواريخ",
        totalNotes: "إجمالي الملاحظات",
        notesByDate: "الملاحظات حسب التاريخ",
        notesCount: "عدد الملاحظات",
        note: "ملاحظة",
        content: "المحتوى",
        overwriteExisting: "الكتابة فوق البيانات الموجودة",
        mergeExisting: "دمج مع البيانات الموجودة",
        preparingExport: "جارٍ تجهيز التصدير",
        // Tooltips
        exportJsonTooltip: "تصدير جميع الملاحظات بتنسيق JSON (مُوصى به للنسخ الاحتياطي)",
        exportCsvTooltip: "تصدير الملاحظات بتنسيق CSV (متوافق مع جداول البيانات)",
        exportTxtTooltip: "تصدير الملاحظات بتنسيق نص عادي (قابل للقراءة البشرية)",
        importTooltip: "استيراد الملاحظات من ملف مُصدّر مسبقًا",
        overwriteTooltip: "استبدال البيانات الموجودة تمامًا بالبيانات المستوردة",
        mergeTooltip: "دمج البيانات المستوردة مع الملاحظات الموجودة"
    }
	},
    fr: {
        title: "Calendrier",
		todayText: "Aujourd'hui",
		notePlaceholder: "Ajoutez votre note ici...",
		save: "Enregistrer",
		close: "Fermer",
		existingNotes: "Notes Existants",
		confirmDelete: "T'es sure d'effacer cette note?",
		validationError: "Veuillez sélectionner une couleur, un type et saisir le texte de la note",
		delete: "effacer",
		storageWarning: "Votre stockage est presque plein. Certaines fonctionnalités peuvent ne pas fonctionner correctement.",
		clearStorage: "Effacer les anciennes données",
		updateAvailable: "Nouvelle version disponible!",
		reload: "Recharger",
		storageCleared: "Anciennes données effacées avec succès",
		storageError: "Erreur lors de la suppression des anciennes données",
		Install: "Installer l'application",
        months: ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"],
        weekdays: ["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"],
        icons: {
            plate: "Assiette",
            health: "Santé",
            mechanics: "Mécanique"
		},
		calendarSystems: {
			gregorian: "Grégorien",
			hijri: "Hijri Islamique"
		},
		monthsHijri: [
			"Mouharram",
			"Safar",
			"Rabi al-Awwal",
			"Rabi ath-Thani",
			"Joumada al-Awwal",
			"Joumada ath-Thani",
			"Rajab",
			"Chaabane",
			"Ramadan",
			"Chawwal",
			"Dhou al-Qi'dah",
			"Dhoul Hijja"
		],
		back: "Retour",
		delai: "Fréquence",
		offlineSave: "Note sauvegardée hors ligne. Synchronisation automatique",
		backgroundSync: "Synchronisation en arrière-plan activée",
		periodicUpdate: "Mises à jour quotidiennes activées",
		notesReminder: "T'as {count} notes pour aujourd'hui",
		dailyTip: "Astuce du jour",
		noTipToday: "Pas d'astuce aujourd'hui",
		noNotesToday: "Pas des notes aujourd'hui",
		sanitizeWarning: "Remarque : Les caractères spéciaux ont été nettoyés automatiquement",
		validationErrorText: "Veuillez saisir le texte de la note",
		edit: "modifier",
		noteSettings: "Paramètres de note",
		noteLabel: "Contenu de la note",
		modalClose: "Fermer la fenêtre",
		onlineStatus: "En ligne",
		offlineStatus: "Hors ligne",
		storageUsage: "Utilisation de {percentage}% du stockage disponible",
		databaseError: "Erreur de base de données. Certaines fonctionnalités peuvent ne pas fonctionner correctement.",
		fileTooLarge: "Le fichier est trop volumineux pour être enregistré hors ligne",
		fileReadError: "Échec de lecture du fichier",
		cleanupError: "Erreur lors du nettoyage",
		loading: "Chargement...",
		noEventsToday: "Aucun événement aujourd'hui",
		addAttachment: "Ajouter une pièce jointe",
		attachmentSaved: "Pièce jointe enregistrée",
		attachmentError: "Échec de l'enregistrement de la pièce jointe",
		noteSaved: "Note enregistrée",
		noteUpdated: "Note mise à jour",
		syncProgress: "Synchronisation en cours...",
		syncCompleted: "Synchronisation terminée",
		syncFailed: "Échec de la synchronisation",
		offlineMessage: "Hors ligne - données non disponibles",
		offlineBadge: "Hors ligne",
		themeToggle: "Basculer en mode sombre",
		searchPlaceholder: "Rechercher des notes...",
		exportButton: "Exporter PDF",
		navigation: {
			scrollUp: "Défiler vers le haut",
			scrollDown: "Défiler vers le bas",
			tipCount: "Astuce {current} sur {total}"
		},
		descriptionLabel: "Descrption",
		frequencyLabel: "Fréquence",
		time: "Heure",
		memory: "Mémoire",
		memoryMonitor: "Moniteur de mémoire",
		clearPartial: "Effacer partiellement les données",
		clearAll: "Effacer toutes les données",
		clearOptions: "Options d'effacement",
		notesByMonth: "Notes par mois",
		clear: "Effacer",
		clearAllWarning: "AVERTISSEMENT : Suppression de données",
		clearAllNotes: "Toutes les notes",
		clearAllAttachments: "Toutes les pièces jointes",
		clearAllSync: "File de synchronisation",
		clearAllLocalStorage: "Données du stockage local",
		clearAllWarningText: "Cette action ne peut pas être annulée. Assurez-vous d'exporter d'abord les données importantes.",
		cancel: "Annuler",
		clearConfirm: "Effacer les données sélectionnées",
		autoCleanup: "Nettoyage automatique",
		autoCleanupTooltip: "Nettoie automatiquement les anciennes données tous les 15 jours",
		monthCleared: "Données du mois effacées",
		confirmDeleteSingleNote: "Supprimer cette note spécifique ?",
		noteDeleted: "Note supprimée",
		attachmentDeleted: "Pièce jointe supprimée",
		deleteError: "Erreur de suppression",
		seeMore: "Voir plus",
		localStorageWarning: "Effacer le stockage local réinitialisera toutes les préférences et données en cache",
		periodicActivities: "activitées periodiques",
		emergencyCleanup: "Nettoyage automatique en cas de stockage plein",
		emergencyCleanupTooltip: "Nettoie automatiquement les anciennes données lorsque le stockage atteint 90% de capacité",
		storageWarning90: "Votre stockage est plein à 90%. Nettoyer les anciennes données ?",
		storageClearing: "Nettoyage des anciennes données pour libérer de l'espace...",
		syncOptions: {
			storage: "Synchroniser le stockage (LocalStorage ↔ DB)",
			storageTooltip: "Garder LocalStorage et IndexedDB synchronisés automatiquement",
			version: "Mise à jour automatique",
			versionTooltip: "Installer automatiquement les nouvelles versions lorsqu'elles sont disponibles",
			calendar: "Synchroniser les systèmes de calendrier",
			calendarTooltip: "Garder les dates grégoriennes et hijri synchronisées",
			newVersion: "Nouvelle version disponible !",
			updating: "Mise à jour vers la nouvelle version..."
		},
		enableNotifications: "Voulez-vous activer les notifications ?",
		testNotification: "Test de notification",
		notificationsUnsupported: "Notifications non prises en charge dans ce navigateur",
		notificationSettings: "Paramètres de notification",
		enableUpdateReminders: "Activer les rappels de mises à jour",
		updateRemindersTooltip: "Recevoir des rappels lorsque des mises à jour sont disponibles",
		enableDailyNotifications: "Activer les notifications quotidiennes",
		dailyNotificationsTooltip: "Recevoir des notifications quotidiennes récapitulatives",
		notificationSound: "Son de notification",
		notificationTime: "Heure de notification",
		soundDefault: "Défaut",
		soundChime: "Carillon", 
		soundBell: "Cloche",
		soundNone: "Aucun",
		memoryManagement: "Gestion de la mémoire",
		synchronization: "Synchronisation",
		storageUsed: "Stockage utilisé",
		syncOptionsTitle: "Synchronisation des données",
		updateOptionsTitle: "Paramètres de mise à jour",
		confirmCleanup: "Procéder au nettoyage automatique ?",
		storageError: "Erreur lors du nettoyage",
		"generalResearch": "Recherche Générale",
		"dateResearch": "Recherche par Date",
		"noteResearch": "Recherche de Notes",
		"generalResearchDesc": "Cela contiendra une fonctionnalité de recherche générale à travers toutes les données.",
		"dateResearchDesc": "Cela contiendra une fonctionnalité de recherche spécifique à la date.",
		"noteResearchDesc": "Cela contiendra une fonctionnalité de recherche du contenu des notes.",
		"searchEverything": "Rechercher tout...",
		"search": "Chercher",
		"findDates": "Trouver des Dates",
		"searchNotes": "Rechercher des Notes",
		"searchAll": "Rechercher tout",
		"searchTips": "Rechercher des astuces",
		"searchAttachments": "Rechercher des pièces jointes",
		"noResultsFound": "Aucun résultat trouvé",
		searchDate: "Recherche par date",
		searchTime: "Recherche par heure",
		searchType: "Recherche par type",
		searchColor: "Recherche par couleur",
		previewText: "Exemple de texte - 123 ABC abc",
        Notesspecials: {
			generalize: "Généraliser la note",
			editSpecial: "Modifier une note spéciale",
			deleteNotes: "Supprimer des notes",
			generalizeTooltip: "Créer des notes répétitives basées sur des modèles",
			editSpecialTooltip: "Modifier les notes spéciales existantes",
			deleteNotesTooltip: "Supprimer une ou plusieurs notes",
			generalizeOptions: "Options de généralisation",
			firstNoteDate: "Date de la première note",
			repeatPattern: "Modèle de répétition",
			includeWeekends: "Inclure les week-ends",
			durationLimit: "Limite de durée",
			daily: "Quotidien",
			weekly: "Hebdomadaire",
			monthly: "Mensuel",
			yearly: "Annuel",
			none: "Aucun",
			saturday: "Samedi",
			sunday: "Dimanche",
			both: "Les deux",
			year: "an",
			years: "ans",
			custom: "Personnalisé",
			confirm: "Confirmer",
			editSpecialNotes: "Modifier les notes spéciales",
			deleteNotesOptions: "Options de suppression",
			deleteSingle: "Supprimer une note",
			deleteAll: "Supprimer toutes les notes",
			confirmDelete: "Confirmer la suppression",
			editSpecialNote: "Modifier une note spéciale",
			selectNoteToDelete: "Sélectionner la note à supprimer",
			confirmDeleteSingle: "Êtes-vous sûr de vouloir supprimer cette note ?",
			confirmDeleteAll: "Êtes-vous sûr de vouloir supprimer TOUTES les notes spéciales ?",
            selectAll: "Tout sélectionner",
            noNotesSelected: "Veuillez sélectionner au moins une note à supprimer",
            confirmDeleteSelected: "Êtes-vous sûr de vouloir supprimer les {0} notes sélectionnées ?"
		},
        hijriConverter: {
            title: "Convertisseur de date Hijri",
        hijriConverterTooltip: "Convertir entre les dates grégoriennes et hijri",
        underDevelopment: "En développement",
            gregorianToHijri: "Grégorien vers Hijri",
            hijriToGregorian: "Hijri vers Grégorien",
            year: "Année",
            month: "Mois",
            day: "Jour",
            convert: "Convertir",
            hijriDate: "Date Hijri",
            gregorianDate: "Date Grégorienne",
            weekday: "Jour de la semaine",
            leapYear: "Année bissextile",
            yes: "Oui",
            no: "Non",
            hijriCalendar: "Calendrier Hijri (Mois en cours)",
            gregorianCalendar: "Calendrier Grégorien (Mois en cours)",
            invalidDate: "Date invalide",
            yearTooltip: "Entrez l'année dans le calendrier grégorien",
            monthTooltip: "Sélectionnez le mois",
            dayTooltip: "Entrez le jour du mois",
            yearInputTooltip: "Entrez une année entre 1 et 9999",
            convertTooltip: "Cliquez pour convertir la date"
        },
    importExport: {
        exportData: "Exporter les données",
        importData: "Importer des données",
        syncStatus: "État de la synchronisation",
        exportDescription: "Exportez vos données de calendrier dans un fichier",
        importDescription: "Importez des données de calendrier à partir d'un fichier",
        exportAs: "Exporter en tant que",
        exporting: "Export en cours",
        importing: "Import en cours",
        exportCompleted: "Export terminé avec succès !",
        exportFailed: "Échec de l'export",
        importComplete: "Import terminé : {importedCount} notes importées, {skippedCount} ignorées",
        importFailed: "Échec de l'import",
        invalidFileFormat: "Format de fichier invalide. Données JSON attendues.",
        invalidDataFormat: "Format de données invalide. Un objet avec des clés de date est attendu.",
        failedToImportNote: "Échec de l'import de la note :",
        calendarNotesExport: "Export des notes de calendrier",
        generated: "Généré",
        totalDates: "Total des dates",
        totalNotes: "Total des notes",
        notesByDate: "Notes par date",
        notesCount: "Nombre de notes",
        note: "Note",
        content: "Contenu",
        overwriteExisting: "Remplacer les données existantes",
        mergeExisting: "Fusionner avec les données existantes",
        preparingExport: "Préparation de l'export",
        // Tooltips
        exportJsonTooltip: "Exporter toutes les notes au format JSON (recommandé pour les sauvegardes)",
        exportCsvTooltip: "Exporter les notes au format CSV (compatible avec les tableurs)",
        exportTxtTooltip: "Exporter les notes au format texte brut (lisible par l'homme)",
        importTooltip: "Importer des notes à partir d'un fichier précédemment exporté",
        overwriteTooltip: "Remplacer complètement les données existantes par les données importées",
        mergeTooltip: "Combiner les données importées avec les notes existantes"
    }
	}
};

// Function to change language
function changeLanguage(lang) {
    const prevSystem = currentCalendarSystem;
    currentLanguage = lang;
    const langData = translations[lang];
    
    // Update calendar system options
    const systemSelect = document.getElementById('calendar-system');
    if (systemSelect) {
        systemSelect.innerHTML = Object.entries(langData.calendarSystems)
        .map(([value, name]) => 
            `<option value="${value}" ${value === prevSystem ? 'selected' : ''}>${name}</option>`
		).join('');
        currentCalendarSystem = prevSystem;
	}
    
    // Update all text elements
    document.querySelector('.title').textContent = langData.title;
    document.getElementById('plate-icon').setAttribute('title', langData.icons.plate);
    document.getElementById('health-icon').setAttribute('title', langData.icons.health);
    document.getElementById('mechanics-icon').setAttribute('title', langData.icons.mechanics);
    document.getElementById('today-btn').innerHTML = `📅 ${langData.todayText}`;
    
    
    // Update settings modal if open
    const settingsModal = document.getElementById('settings-modal');
    const isSettingsOpen = settingsModal && settingsModal.style.display === 'block';
    
    if (window.settingsManager) {
        window.settingsManager.updateLanguageTexts();
    }
    // Update weekdays in calendar header
    const weekdays = document.querySelectorAll('.weekdays div');
    if (weekdays.length === 7) {
        weekdays.forEach((day, index) => {
            day.textContent = langData.weekdays[index];
		});
	}
    
    // Update calendar immediately
    renderCalendar(langData);
    
    // Set document direction
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    
    return langData;
}
// Initialize language
/* let currentLanguage = 'en'; */	