// Language translations
const translations = {
    en: {
        title: "Calendar",
		todayText: "Today",
		notePlaceholder: "Add your note here...",
		save: "Save",
		close: "Close",
		existingNotes: "Existing Notes",
		validationError: "Please select a color, type and enter note text",
		delete: "Delete",
		confirmDelete: "Are you sure you want to delete this note?",
		storageWarning: "Your storage is almost full. Some features may not work properly.",
		clearStorage: "Clear old data",
		updateAvailable: "New version available!",
		reload: "Reload",
		storageCleared: "Old data cleared successfully",
		storageError: "Error clearing old data",
		Install: "Install App",
        months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        icons: {
            plate: "Plate",
            health: "Health",
            mechanics: "Mechanics"
		},
		calendarSystems: {
			gregorian: "Gregorian",
			hijri: "Islamic Hijri"
		},
		monthsHijri: [
			"Muharram",
			"Safar",
			"Rabi' al-Awwal",
			"Rabi' al-Thani",
			"Jumada al-Awwal",
			"Jumada al-Thani",
			"Rajab",
			"Sha'ban",
			"Ramadan",
			"Shawwal",
			"Dhu al-Qidah",
			"Dhul-Hijjah"
		],
		back: "Back",
		delai: "Frequency",
		offlineSave: "Note saved offline. Will sync when online",
		backgroundSync: "Background sync active",
		periodicUpdate: "Daily updates enabled",
		notesReminder: "You have {count} notes for today",
		dailyTip: "Daily Tip",
		noTipToday: "No tip for today",
		noNotesToday: "No notes for today",
		sanitizeWarning: "Note : Special caracters will be cleaned automatically",
		validationErrorText: "Enter the note's text",
		edit: "Edit",
		noteSettings: "Note Settings",
		noteLabel: "Note Content",
		modalClose: "Close modal",
		onlineStatus: "Online",
		offlineStatus: "Offline",
		storageUsage: "Using {percentage}% of available storage",
		databaseError: "Database error. Some features may not work properly.",
		fileTooLarge: "File is too large to save offline",
		fileReadError: "Failed to read file",
		cleanupError: "Error during cleanup",
		loading: "Loading...",
		noEventsToday: "No events today",
		addAttachment: "Add attachment",
		attachmentSaved: "Attachment saved",
		attachmentError: "Failed to save attachment",
		noteSaved: "Note saved",
		noteUpdated: "Note updated",
		syncProgress: "Sync in progress...",
		syncCompleted: "Sync completed",
		syncFailed: "Sync failed",
		offlineMessage: "Offline - data unavailable",
		offlineBadge: "Offline",
		themeToggle: "Toggle Dark Mode",
		searchPlaceholder: "Search notes...",
		exportButton: "Export PDF",
		navigation: {
			scrollUp: "Scroll up",
			scrollDown: "Scroll down",
			tipCount: "Tip {current} of {total}"
		},
		descriptionLabel: "Description", // For the "📝" label
		frequencyLabel: "Frequency",     // For the "⏰" label
		time: "Time",
		memory: "Memory",
		memoryMonitor: "Memory Monitor",
		clearPartial: "Clear Partial Data",
		clearAll: "Clear All Data",
		clearOptions: "Clear Options",
		notesByMonth: "Notes by Month",
		clear: "Clear",
		clearAllWarning: "WARNING: Data Deletion",
		clearAllNotes: "All notes",
		clearAllAttachments: "All attachments",
		clearAllSync: "Sync queue",
		clearAllLocalStorage: "LocalStorage data",
		clearAllWarningText: "This action cannot be undone. Make sure to export important data first.",
		cancel: "Cancel",
		clearConfirm: "Clear Selected Data",
		autoCleanup: "Automatic Cleanup",
		autoCleanupTooltip: "Automatically cleans old data every 15 days",
		monthCleared: "Month data cleared",
		confirmDeleteSingleNote: "Delete this specific note?",
		noteDeleted: "Note deleted",
		attachmentDeleted: "Attachment deleted",
		deleteError: "Error deleting",
		seeMore: "See More",
		localStorageWarning: "Clearing localStorage will reset all preferences and cached data",
		periodicActivities: "Periodic Activities",
		emergencyCleanup: "Auto-clean when storage full",
		emergencyCleanupTooltip: "Automatically cleans old data when storage reaches 90% capacity",
		storageWarning90: "Your storage is 90% full. Clean old data?",
		storageClearing: "Cleaning old data to free space...",
		syncOptions: {
			storage: "Sync Storage (LocalStorage ↔ DB)",
			storageTooltip: "Keep LocalStorage and IndexedDB in sync automatically",
			version: "Auto-update App",
			versionTooltip: "Automatically install new versions when available",
			calendar: "Sync Calendar Systems",
			calendarTooltip: "Keep Gregorian and Hijri dates synchronized",
			newVersion: "New version available!",
			updating: "Updating to new version..."
		},
		enableNotifications: "Would you like to enable notifications?",
		testNotification: "Test Notification",
		notificationsUnsupported: "Notifications not supported in this browser",
		notificationSettings: "Notification Settings",
		enableUpdateReminders: "Enable updates reminders",
		updateRemindersTooltip: "Get reminders when updates are available",
		enableDailyNotifications: "Enable daily notifications",
		dailyNotificationsTooltip: "Receive daily summary notifications",
		notificationSound: "Notification sound", 
		notificationTime: "Notification time",
		soundDefault: "Default",
		soundChime: "Chime", 
		soundBell: "Bell",
		soundNone: "None",
		memoryManagement: "Memory Management",
		synchronization: "Synchronization",
		storageUsed: "Storage Used",
		syncOptionsTitle: "Data Synchronization",
		updateOptionsTitle: "Update Settings",
		confirmCleanup: "Proceed with automatic cleanup?",
		generalResearch: "General Research",
		dateResearch: "Date Research",
		noteResearch: "Note Research",
		generalResearchDesc: "This will contain general search functionality across all data.",
		dateResearchDesc: "This will contain date-specific search functionality.",
		noteResearchDesc: "This will contain note content search functionality.",
		searchEverything: "Search everything...",
		search: "Search",
		findDates: "Find Dates",
		searchNotes: "Search Notes",
searchAll: "Search All",
searchTips: "Search Tips", 
searchAttachments: "Search Attachments",
noResultsFound: "No results found",
  searchDate: "Search by Date",
  searchTime: "Search by Time",
  searchType: "Search by Type",
  searchColor: "Search by Color"
	},
    ar: {
        title: "التقويم",
		todayText: "اليوم",
		notePlaceholder: "أضف ملاحظتك هنا...",
		save: "حفظ",
		close: "إغلاق",
		existingNotes: "الملاحظات الموجودة",
		validationError: "الرجاء اختيار لون ونوع وإدخال نص الملاحظة",
		delete: "مسح",
		confirmDelete: "هل أنت متأكد أنك تريد محو الملاحظة؟",
		storageWarning: "التخزين شبه ممتلئ. قد لا تعمل بعض الميزات بشكل صحيح.",
		clearStorage: "مسح البيانات القديمة",
		updateAvailable: "نسخة جديدة متوفرة!",
		reload: "إعادة التحميل",
		storageCleared: "تم مسح البيانات القديمة بنجاح",
		storageError: "خطأ أثناء مسح البيانات القديمة",
		Install: "تثبيت التطبيق",
        months: ["جانفي", "فيفري", "مارس", "أفريل", "ماي", "جوان", "جويلية", "أوت", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"],
        weekdays: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"],
        icons: {
            plate: "الطعام",
            health: "الصحة",
            mechanics: "الميكانيكا"
		},
		calendarSystems: {
			gregorian: "الميلادي",
			hijri: "الهجري"
		},
		monthsHijri: [
			"محرم",
			"صفر",
			"ربيع الأول",
			"ربيع الآخر",
			"جمادى الأولى",
			"جمادى الآخرة",
			"رجب",
			"شعبان",
			"رمضان",
			"شوال",
			"ذو القعدة",
			"ذو الحجة"
		],
		back: "رجوع",
		delai: "التكرار",
		offlineSave: "تم حفظ الملاحظة بدون اتصال. سيتم المزامنة عند الاتصال",
		backgroundSync: "مزامنة الخلفية نشطة",
		periodicUpdate: "تم تفعيل التحديثات اليومية",
		notesReminder: "لديك {count} ملاحظات لليوم",
		dailyTip: "نصيحة اليوم",
		noTipToday: "لا ملاحظات اليوم",
		noNotesToday: "لا ملاحظات اليوم",
		sanitizeWarning: "ملاحظة: تم تنظيف الأحرف الخاصة تلقائيًا",
		validationErrorText: "الرجاء إدخال نص الملاحظة",
		edit: "عدل",
		noteSettings: "إعدادات الملاحظة",
		noteLabel: "محتويات الملاحظة",
		modalClose: "إغلاق النافذة",
		onlineStatus: "متصل بالإنترنت",
		offlineStatus: "غير متصل",
		storageUsage: "يتم استخدام {percentage}٪ من مساحة التخزين المتاحة",
		databaseError: "خطأ في قاعدة البيانات. بعض الميزات قد لا تعمل بشكل صحيح.",
		fileTooLarge: "الملف كبير جدًا ولا يمكن حفظه دون اتصال",
		fileReadError: "فشل قراءة الملف",
		cleanupError: "خطأ أثناء التنظيف",
		loading: "جاري التحميل...",
		noEventsToday: "لا توجد أحداث اليوم",
		addAttachment: "إضافة مرفق",
		attachmentSaved: "تم حفظ المرفق",
		attachmentError: "فشل حفظ المرفق",
		noteSaved: "تم حفظ الملاحظة",
		noteUpdated: "تم تحديث الملاحظة",
		syncProgress: "جاري المزامنة...",
		syncCompleted: "تمت المزامنة",
		syncFailed: "فشلت المزامنة",
		offlineMessage: "غير متصل - البيانات غير متوفرة",
		offlineBadge: "غير متصل",
		themeToggle: "تبديل الوضع المظلم", 
		searchPlaceholder: "ابحث في الملاحظات...",
		exportButton: "تصدير PDF",
		navigation: {
			scrollUp: "التمرير لأعلى",
			scrollDown: "التمرير لأسفل",
			tipCount: "النصيحة {current} من {total}"
		},
		descriptionLabel: "الوصف",
		frequencyLabel: "التكرار",
		time: "وقت",
		memory: "الذاكرة",
		memoryMonitor: "مراقبة الذاكرة",
		clearPartial: "مسح جزئي للبيانات",
		clearAll: "مسح جميع البيانات",
		clearOptions: "خيارات المسح",
		notesByMonth: "الملاحظات حسب الشهر",
		clear: "مسح",
		clearAllWarning: "تحذير: حذف البيانات",
		clearAllNotes: "جميع الملاحظات",
		clearAllAttachments: "جميع المرفقات",
		clearAllSync: "طابور المزامنة",
		clearAllLocalStorage: "بيانات التخزين المحلي",
		clearAllWarningText: "لا يمكن التراجع عن هذا الإجراء. تأكد من تصدير البيانات المهمة أولاً.",
		cancel: "إلغاء",
		clearConfirm: "مسح البيانات المحددة",
		autoCleanup: "تنظيف تلقائي",
		autoCleanupTooltip: "تنظيف البيانات القديمة تلقائيًا كل 15 يومًا",
		monthCleared: "تم مسح بيانات الشهر",
		confirmDeleteSingleNote: "هل تريد حذف هذه الملاحظة المحددة؟",
		noteDeleted: "تم حذف الملاحظة",
		attachmentDeleted: "تم حذف المرفق",
		deleteError: "خطأ في الحذف",
		seeMore: "عرض المزيد",
		localStorageWarning: "مسح التخزين المحلي سيعيد تعيين جميع التفضيلات والبيانات المخزنة مؤقتًا",
		periodicActivities: "العمليات الدورية",
		emergencyCleanup: "تنظيف تلقائي عند امتلاء التخزين",
		emergencyCleanupTooltip: "يقوم بتنظيف البيانات القديمة تلقائيًا عندما يصل التخزين إلى 90% من السعة",
		storageWarning90: "التخزين ممتلئ بنسبة 90%. هل تريد تنظيف البيانات القديمة؟",
		storageClearing: "جاري تنظيف البيانات القديمة لتوفير مساحة...",
		syncOptions: {
			storage: "مزامنة التخزين (LocalStorage ↔ قاعدة البيانات)",
			storageTooltip: "الحفاظ على مزامنة LocalStorage و IndexedDB تلقائيًا",
			version: "تحديث التطبيق التلقائي",
			versionTooltip: "تثبيت الإصدارات الجديدة تلقائيًا عند توفرها",
			calendar: "مزامنة أنظمة التقويم",
			calendarTooltip: "الحفاظ على تواريخ التقويم الميلادي والهجري متزامنة",
			newVersion: "إصدار جديد متاح!",
			updating: "جارٍ التحديث إلى الإصدار الجديد..."
		},
		enableNotifications: "هل ترغب في تمكين الإشعارات؟",
		testNotification: "اختبار الإشعار",
		notificationsUnsupported: "الإشعارات غير مدعومة في هذا المتصفح",
		notificationSettings: "إعدادات الإشعارات",
		enableUpdateReminders: "تمكين تذكير التحديثات",
		updateRemindersTooltip: "الحصول على تذكير عند توفر التحديثات",
		enableDailyNotifications: "تمكين الإشعارات اليومية",
		dailyNotificationsTooltip: "تلقي إشعارات يومية ملخصة",
		notificationSound: "صوت الإشعار",
		notificationTime: "وقت الإشعار", 
		soundDefault: "افتراضي",
		soundChime: "جرس",
		soundBell: "جرس كبير",
		soundNone: "بلا",
		memoryManagement: "إدارة الذاكرة",
		synchronization: "المزامنة",
		storageUsed: "التخزين المستخدم",
		syncOptionsTitle: "مزامنة البيانات",
		updateOptionsTitle: "إعدادات التحديث",
		confirmCleanup: "المتابعة بالتنظيف التلقائي؟",
		storageError: "خطأ أثناء التنظيف",
		"generalResearch": "البحث العام",
		"dateResearch": "تاريخ البحث",
		"noteResearch": "ملاحظة البحث",
		"generalResearchDesc": "سيحتوي هذا على وظيفة البحث العامة عبر جميع البيانات.",
		"dateResearchDesc": "سيحتوي هذا على وظيفة البحث المتعلقة بالتاريخ.",
		"noteResearchDesc": "سيحتوي هذا على وظيفة البحث عن محتوى الملاحظات.",
		"searchEverything": "ابحث عن كل شيء...",
		"search": "بحث",
		"findDates": "ابحث عن التواريخ",
		"searchNotes": "ابحث عن الملاحظات",
"searchAll": "البحث في الكل",
"searchTips": "البحث في النصائح",
"searchAttachments": "البحث في المرفقات", 
"noResultsFound": "لا توجد نتائج",
  searchDate: "البحث حسب التاريخ",
  searchTime: "البحث حسب الوقت",
  searchType: "البحث حسب النوع",
  searchColor: "البحث حسب اللون"
	},
    fr: {
        title: "Calendrier",
		todayText: "Aujourd'hui",
		notePlaceholder: "Ajoutez votre note ici...",
		save: "Enregistrer",
		close: "Fermer",
		existingNotes: "Notes Existants",
		confirmDelete: "T'es sure d'effacer cette note?",
		validationError: "Veuillez sélectionner une couleur, un type et saisir le texte de la note",
		delete: "effacer",
		storageWarning: "Votre stockage est presque plein. Certaines fonctionnalités peuvent ne pas fonctionner correctement.",
		clearStorage: "Effacer les anciennes données",
		updateAvailable: "Nouvelle version disponible!",
		reload: "Recharger",
		storageCleared: "Anciennes données effacées avec succès",
		storageError: "Erreur lors de la suppression des anciennes données",
		Install: "Installer l'application",
        months: ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"],
        weekdays: ["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"],
        icons: {
            plate: "Assiette",
            health: "Santé",
            mechanics: "Mécanique"
		},
		calendarSystems: {
			gregorian: "Grégorien",
			hijri: "Hijri Islamique"
		},
		monthsHijri: [
			"Mouharram",
			"Safar",
			"Rabi al-Awwal",
			"Rabi ath-Thani",
			"Joumada al-Awwal",
			"Joumada ath-Thani",
			"Rajab",
			"Chaabane",
			"Ramadan",
			"Chawwal",
			"Dhou al-Qi'dah",
			"Dhoul Hijja"
		],
		back: "Retour",
		delai: "Fréquence",
		offlineSave: "Note sauvegardée hors ligne. Synchronisation automatique",
		backgroundSync: "Synchronisation en arrière-plan activée",
		periodicUpdate: "Mises à jour quotidiennes activées",
		notesReminder: "T'as {count} notes pour aujourd'hui",
		dailyTip: "Astuce du jour",
		noTipToday: "Pas d'astuce aujourd'hui",
		noNotesToday: "Pas des notes aujourd'hui",
		sanitizeWarning: "Remarque : Les caractères spéciaux ont été nettoyés automatiquement",
		validationErrorText: "Veuillez saisir le texte de la note",
		edit: "modifier",
		noteSettings: "Paramètres de note",
		noteLabel: "Contenu de la note",
		modalClose: "Fermer la fenêtre",
		onlineStatus: "En ligne",
		offlineStatus: "Hors ligne",
		storageUsage: "Utilisation de {percentage}% du stockage disponible",
		databaseError: "Erreur de base de données. Certaines fonctionnalités peuvent ne pas fonctionner correctement.",
		fileTooLarge: "Le fichier est trop volumineux pour être enregistré hors ligne",
		fileReadError: "Échec de lecture du fichier",
		cleanupError: "Erreur lors du nettoyage",
		loading: "Chargement...",
		noEventsToday: "Aucun événement aujourd'hui",
		addAttachment: "Ajouter une pièce jointe",
		attachmentSaved: "Pièce jointe enregistrée",
		attachmentError: "Échec de l'enregistrement de la pièce jointe",
		noteSaved: "Note enregistrée",
		noteUpdated: "Note mise à jour",
		syncProgress: "Synchronisation en cours...",
		syncCompleted: "Synchronisation terminée",
		syncFailed: "Échec de la synchronisation",
		offlineMessage: "Hors ligne - données non disponibles",
		offlineBadge: "Hors ligne",
		themeToggle: "Basculer en mode sombre",
		searchPlaceholder: "Rechercher des notes...",
		exportButton: "Exporter PDF",
		navigation: {
			scrollUp: "Défiler vers le haut",
			scrollDown: "Défiler vers le bas",
			tipCount: "Astuce {current} sur {total}"
		},
		descriptionLabel: "Descrption",
		frequencyLabel: "Fréquence",
		time: "Heure",
		memory: "Mémoire",
		memoryMonitor: "Moniteur de mémoire",
		clearPartial: "Effacer partiellement les données",
		clearAll: "Effacer toutes les données",
		clearOptions: "Options d'effacement",
		notesByMonth: "Notes par mois",
		clear: "Effacer",
		clearAllWarning: "AVERTISSEMENT : Suppression de données",
		clearAllNotes: "Toutes les notes",
		clearAllAttachments: "Toutes les pièces jointes",
		clearAllSync: "File de synchronisation",
		clearAllLocalStorage: "Données du stockage local",
		clearAllWarningText: "Cette action ne peut pas être annulée. Assurez-vous d'exporter d'abord les données importantes.",
		cancel: "Annuler",
		clearConfirm: "Effacer les données sélectionnées",
		autoCleanup: "Nettoyage automatique",
		autoCleanupTooltip: "Nettoie automatiquement les anciennes données tous les 15 jours",
		monthCleared: "Données du mois effacées",
		confirmDeleteSingleNote: "Supprimer cette note spécifique ?",
		noteDeleted: "Note supprimée",
		attachmentDeleted: "Pièce jointe supprimée",
		deleteError: "Erreur de suppression",
		seeMore: "Voir plus",
		localStorageWarning: "Effacer le stockage local réinitialisera toutes les préférences et données en cache",
		periodicActivities: "activitées periodiques",
		emergencyCleanup: "Nettoyage automatique en cas de stockage plein",
		emergencyCleanupTooltip: "Nettoie automatiquement les anciennes données lorsque le stockage atteint 90% de capacité",
		storageWarning90: "Votre stockage est plein à 90%. Nettoyer les anciennes données ?",
		storageClearing: "Nettoyage des anciennes données pour libérer de l'espace...",
		syncOptions: {
			storage: "Synchroniser le stockage (LocalStorage ↔ DB)",
			storageTooltip: "Garder LocalStorage et IndexedDB synchronisés automatiquement",
			version: "Mise à jour automatique",
			versionTooltip: "Installer automatiquement les nouvelles versions lorsqu'elles sont disponibles",
			calendar: "Synchroniser les systèmes de calendrier",
			calendarTooltip: "Garder les dates grégoriennes et hijri synchronisées",
			newVersion: "Nouvelle version disponible !",
			updating: "Mise à jour vers la nouvelle version..."
		},
		enableNotifications: "Voulez-vous activer les notifications ?",
		testNotification: "Test de notification",
		notificationsUnsupported: "Notifications non prises en charge dans ce navigateur",
		notificationSettings: "Paramètres de notification",
		enableUpdateReminders: "Activer les rappels de mises à jour",
		updateRemindersTooltip: "Recevoir des rappels lorsque des mises à jour sont disponibles",
		enableDailyNotifications: "Activer les notifications quotidiennes",
		dailyNotificationsTooltip: "Recevoir des notifications quotidiennes récapitulatives",
		notificationSound: "Son de notification",
		notificationTime: "Heure de notification",
		soundDefault: "Défaut",
		soundChime: "Carillon", 
		soundBell: "Cloche",
		soundNone: "Aucun",
		memoryManagement: "Gestion de la mémoire",
		synchronization: "Synchronisation",
		storageUsed: "Stockage utilisé",
		syncOptionsTitle: "Synchronisation des données",
		updateOptionsTitle: "Paramètres de mise à jour",
		confirmCleanup: "Procéder au nettoyage automatique ?",
		storageError: "Erreur lors du nettoyage",
		"generalResearch": "Recherche Générale",
		"dateResearch": "Recherche par Date",
		"noteResearch": "Recherche de Notes",
		"generalResearchDesc": "Cela contiendra une fonctionnalité de recherche générale à travers toutes les données.",
		"dateResearchDesc": "Cela contiendra une fonctionnalité de recherche spécifique à la date.",
		"noteResearchDesc": "Cela contiendra une fonctionnalité de recherche du contenu des notes.",
		"searchEverything": "Rechercher tout...",
		"search": "Chercher",
		"findDates": "Trouver des Dates",
		"searchNotes": "Rechercher des Notes",
"searchAll": "Rechercher tout",
"searchTips": "Rechercher des astuces",
"searchAttachments": "Rechercher des pièces jointes",
"noResultsFound": "Aucun résultat trouvé",
  searchDate: "Recherche par date",
  searchTime: "Recherche par heure",
  searchType: "Recherche par type",
  searchColor: "Recherche par couleur"
	}
};

// Function to change language
function changeLanguage(lang) {
    const prevSystem = currentCalendarSystem;
    currentLanguage = lang;
    const langData = translations[lang];
    
    // Update calendar system options
    const systemSelect = document.getElementById('calendar-system');
    if (systemSelect) {
        systemSelect.innerHTML = Object.entries(langData.calendarSystems)
        .map(([value, name]) => 
            `<option value="${value}" ${value === prevSystem ? 'selected' : ''}>${name}</option>`
		).join('');
        currentCalendarSystem = prevSystem;
	}
    
    // Update all text elements
    document.querySelector('.title').textContent = langData.title;
    document.getElementById('plate-icon').setAttribute('title', langData.icons.plate);
    document.getElementById('health-icon').setAttribute('title', langData.icons.health);
    document.getElementById('mechanics-icon').setAttribute('title', langData.icons.mechanics);
    document.getElementById('today-btn').innerHTML = `📅 ${langData.todayText}`;
    
    
    // Update settings modal if open
    const settingsModal = document.getElementById('settings-modal');
    const isSettingsOpen = settingsModal && settingsModal.style.display === 'block';
    
    if (window.settingsManager) {
        window.settingsManager.updateLanguageTexts();
	}
    // Update weekdays in calendar header
    const weekdays = document.querySelectorAll('.weekdays div');
    if (weekdays.length === 7) {
        weekdays.forEach((day, index) => {
            day.textContent = langData.weekdays[index];
		});
	}
    
    // Update calendar immediately
    renderCalendar(langData);
    
    // Set document direction
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    
    return langData;
}
// Initialize language
/* let currentLanguage = 'en'; */	